spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_consumer
    username: root
    password: Arikaran@491284
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8081
