spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Arikaran@491284
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
